### ISSUE TITLE
Re add the level design section at the bottom please

### ISSUE THREAD

**Issue by Smcart** [Smcart/smcart.github.io#5]
If you can add back in the level design section that was removed to the bottom of the page

![image](https://github.com/Smcart/smcart.github.io/assets/62849287/5328107f-281d-4db9-af82-31368d261347)

**Comment by yerbestpal** [comment]
It would be honour.

**Comment by yerbestpal** [comment]
@Smcart Done.

**Comment by Smcart** [comment]
Thank you brother.
